require 'rake'
require 'spec/rake/spectask'
require 'spec/rake/verify_rcov'

task :default => :spec

desc "Run all specs"
Spec::Rake::SpecTask.new('spec') do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
end

desc "Run all specs with rcov"
Spec::Rake::SpecTask.new('spec_rcov') do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
  t.rcov = true
  t.rcov_opts = ['--text-report', '--exclude', 'spec/']
  t.rcov_dir    = 'doc/coverage'
end

RCov::VerifyTask.new(:verify_rcov => :spec_rcov) do |t|
  t.threshold = 100.0
  t.index_html = 'doc/coverage/index.html'
end